language: node_js
node_js:
  - 13
  - 12
  - 10
after_success: npm run coveralls
stages:
  - test
  - name: npm release
    if: tag IS present
jobs:
  include:
    - stage: npm release
      install: skip
      script: skip
      after_success: true # skip step with success exit code
      deploy:
        provider: npm
        email: nwoltman@outlook.com
        on:
          tags: true
        api_key:
          secure: DOw8AAMwGJG7lGwxXd7sqYeGkYjX+HK+mpFnabyi3ppm06sxjQ/pk1ofA/Sz3o4fYZ1X1+v2Jkgrba4ixCOKAM3/A8Tcfn6lAI7xJUjACmwnGDvJ5iAlo5AoLSg8XWTdw4/IZbVDkXsE+Q+SlY5aRt0aa26z21M+QOcRRbseExKsPblDlkNW7S1H6raDh53VCVZf5TBBdLEYAE1Xgk3R+21ZDC0V9fqX/JDer15J6nBQYQHlpP2gu07l1mjkpjHYedM9NNfqkK1QL8dqE2iFaG3zyNVeMuCayLbqQXfxTeVGj/jfS/1bZwX19iaovQLchErQwfdUfKmb3vWTVcuAJ1ajmMRXi1hq1oksuuFfhrLo+uApxyIIrX/iaX8b2c1s0paYbhPLBJlYYHP/RRWJCPF+D2g0fBv0eFM6rDEJlqai4yvtg5ceH2rB+i2hA4twnoRVTOOhNC3hS/i0X2lQZ4owcuLaw+O7N1iBSkt9flBw2+EPIGphzzpH82V+8r4j8Ai7PjZHhC9FfQK45/TdhX1wUdanIDyc3WsNheLUelzifuEkL/1JZ8GgPnNi7IYZYSwCzqcixv43zlfv5G1m3oXpu8KFB0YCbu6382yxW2cMAi8Wx9OlS2vd6t3sa916vfrF0V+hGtvx+n5rdUS9sYv3jDsqLbwNxt8MMvDE8Q0=
