language: node_js
node_js:
  - '6'
  - '8'
  - '9'
after_success: npm run coveralls
deploy:
  provider: npm
  email: nwoltman@outlook.com
  on:
    tags: true
  api_key:
    secure: FLnIc7RvDgMcGqEC+iK5aOHGVYqVLPO4xJ/6zUWTKIA8gai783W/UChf+QGhOQ4cwMTlnryO2vZ4mMawzKie/Y0oo6kY7IoFJxNC+24fMf+iEDyOb/YluoIK99MtyMsqeZtyTUwLVLpYwZwXmrdu0qCjv9OHC3XJo+8EG4tnBJ0bVjNiz+mTuTTR0nnI8iEKXsP4+vnXAO9TMpis/kiGb3GyPKBHEyyawIcHputT4xY8u5NHxuwKr44zo3qJoeWkXQbUAo/B8pyk2+2xq1GgGKK3j7esPkddX2UWhm07C4KjZFDSo8YHHHwHNMqmQ/X34cOpwlfPU0zkeG/7nZl3kttTFu6sFmgFk22oo7rtKTQsH7cYFysryPr0ZIhRyvE7dMIdIpe7ejM50f36l0/xMnxUz7DtbSxQV3XNcr7u31SL0XivUKDSI0tBh/lBL5UwG6zqYzuYZ7UnlBlo0h3gdWqy+1zHSqXagCW4Hsc6mmorDo/DOl6PMGjeIDXkL5afdtV7gBKMZ9bwjWGnoQW3VKOEEuk3oN+97rmeMPgN4EquJz8ZFxwNZHByQ6RDfxLzpeb6aosszwFVNpJ20svBJtIHXs/La1hmGQcdDpEYMpRjtR270+JElMvM7GHYkejb9dZWfjqD1rmYW6t67gxNFy6DcLn7bPcKIndnom8Kkds=
